// AUTO-GENERATED by scripts/build-peeps.mjs — do not edit by hand.
// OpenPeeps flat figures (CC0), tinted via currentColor.

export type PeepMeta = { id: string; w: number; h: number };

export const PEEPS: PeepMeta[] = [
  {
    "id": "peep-standing-1",
    "w": 213,
    "h": 715
  },
  {
    "id": "peep-standing-2",
    "w": 213,
    "h": 733
  },
  {
    "id": "peep-standing-3",
    "w": 213,
    "h": 701
  },
  {
    "id": "peep-standing-4",
    "w": 304,
    "h": 681
  },
  {
    "id": "peep-standing-5",
    "w": 304,
    "h": 680
  },
  {
    "id": "peep-standing-6",
    "w": 304,
    "h": 677
  },
  {
    "id": "peep-standing-7",
    "w": 249,
    "h": 686
  },
  {
    "id": "peep-standing-8",
    "w": 249,
    "h": 679
  },
  {
    "id": "peep-standing-9",
    "w": 249,
    "h": 672
  },
  {
    "id": "peep-standing-10",
    "w": 255,
    "h": 688
  },
  {
    "id": "peep-standing-11",
    "w": 260,
    "h": 674
  },
  {
    "id": "peep-standing-12",
    "w": 255,
    "h": 710
  },
  {
    "id": "peep-standing-13",
    "w": 256,
    "h": 679
  },
  {
    "id": "peep-standing-14",
    "w": 256,
    "h": 687
  },
  {
    "id": "peep-standing-15",
    "w": 256,
    "h": 682
  },
  {
    "id": "peep-standing-16",
    "w": 309,
    "h": 652
  },
  {
    "id": "peep-standing-17",
    "w": 309,
    "h": 617
  },
  {
    "id": "peep-standing-18",
    "w": 249,
    "h": 680
  },
  {
    "id": "peep-standing-19",
    "w": 198,
    "h": 670
  },
  {
    "id": "peep-standing-20",
    "w": 213,
    "h": 706
  },
  {
    "id": "peep-standing-21",
    "w": 198,
    "h": 669
  },
  {
    "id": "peep-standing-22",
    "w": 321,
    "h": 691
  },
  {
    "id": "peep-standing-23",
    "w": 321,
    "h": 699
  },
  {
    "id": "peep-standing-24",
    "w": 321,
    "h": 692
  },
  {
    "id": "peep-standing-25",
    "w": 246,
    "h": 713
  },
  {
    "id": "peep-standing-26",
    "w": 246,
    "h": 677
  },
  {
    "id": "peep-standing-27",
    "w": 246,
    "h": 713
  },
  {
    "id": "peep-standing-28",
    "w": 213,
    "h": 694
  },
  {
    "id": "peep-standing-29",
    "w": 213,
    "h": 689
  },
  {
    "id": "peep-standing-30",
    "w": 213,
    "h": 701
  },
  {
    "id": "peep-sitting-1",
    "w": 346,
    "h": 510
  },
  {
    "id": "peep-sitting-2",
    "w": 346,
    "h": 521
  },
  {
    "id": "peep-sitting-3",
    "w": 853,
    "h": 798
  },
  {
    "id": "peep-sitting-4",
    "w": 340,
    "h": 465
  },
  {
    "id": "peep-sitting-5",
    "w": 340,
    "h": 469
  },
  {
    "id": "peep-sitting-6",
    "w": 365,
    "h": 577
  },
  {
    "id": "peep-sitting-7",
    "w": 367,
    "h": 620
  },
  {
    "id": "peep-sitting-8",
    "w": 853,
    "h": 799
  },
  {
    "id": "peep-sitting-9",
    "w": 324,
    "h": 467
  },
  {
    "id": "peep-sitting-10",
    "w": 324,
    "h": 484
  },
  {
    "id": "peep-sitting-11",
    "w": 335,
    "h": 495
  },
  {
    "id": "peep-sitting-12",
    "w": 336,
    "h": 504
  },
  {
    "id": "peep-sitting-13",
    "w": 853,
    "h": 844
  },
  {
    "id": "peep-sitting-14",
    "w": 462,
    "h": 603
  },
  {
    "id": "peep-sitting-15",
    "w": 462,
    "h": 625
  },
  {
    "id": "peep-sitting-16",
    "w": 853,
    "h": 825
  },
  {
    "id": "peep-sitting-17",
    "w": 365,
    "h": 576
  },
  {
    "id": "peep-sitting-18",
    "w": 346,
    "h": 501
  }
];

export const PEEP_IDS: string[] = PEEPS.map((p) => p.id);

const BY_ID: Record<string, PeepMeta> = Object.fromEntries(
  PEEPS.map((p) => [p.id, p]),
);

export function peepMeta(id: string | null | undefined): PeepMeta | null {
  if (!id) return null;
  return BY_ID[id] ?? null;
}
