// Processes the OpenPeeps "Flat Assets" (CC0) standing + sitting figures into
// tintable SVGs the app can recolour to any ink colour.
//
//   - replaces the black line/fill (#000000) with `currentColor` so a wrapping
//     element's `color` tints the whole figure; white details stay white
//   - strips the root width/height (keeps viewBox) so the figure scales freely
//   - writes cleaned files to public/peeps/<id>.svg
//   - emits src/lib/peeps.generated.ts: the id list + per-id viewBox dims
//
// Re-runnable. Source lives in OpenPeeps_downloads/ (gitignored); the cleaned
// output IS committed (OpenPeeps is CC0 / public domain).
//
// Run: node scripts/build-peeps.mjs

import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const SRC_BASE = join(
  ROOT,
  "OpenPeeps_downloads/_extracted/Flat Assets/Templates",
);
const SETS = [
  { dir: "Standing", prefix: "peep-standing-" },
  { dir: "Sitting", prefix: "peep-sitting-" },
];
const OUT_DIR = join(ROOT, "public/peeps");
const MANIFEST = join(ROOT, "src/lib/peeps.generated.ts");

function clean(svg) {
  let out = svg;
  // Drop the XML prolog / comments / Sketch metadata noise.
  out = out.replace(/<\?xml[^>]*\?>/g, "");
  out = out.replace(/<!--[\s\S]*?-->/g, "");
  out = out.replace(/<title>[\s\S]*?<\/title>/g, "");
  out = out.replace(/<desc>[\s\S]*?<\/desc>/g, "");
  // Tint: black -> currentColor (covers fill="#000000", #000, and the stray accent).
  out = out.replace(/#000000/gi, "currentColor");
  out = out.replace(/#000\b/gi, "currentColor");
  out = out.replace(/#4F66AF/gi, "currentColor");
  // Strip explicit pixel width/height on the root <svg> so it scales to its box.
  out = out.replace(/(<svg\b[^>]*?)\swidth="[^"]*"/i, "$1");
  out = out.replace(/(<svg\b[^>]*?)\sheight="[^"]*"/i, "$1");
  // Reduce coordinate precision (Sketch exports ~6 decimals) to 1 decimal —
  // invisible at the sizes we render, and roughly halves file size.
  out = out.replace(/-?\d+\.\d{2,}/g, (m) => String(Math.round(parseFloat(m) * 10) / 10));
  // Collapse the inter-tag whitespace Sketch leaves behind.
  out = out.replace(/>\s+</g, "><");
  return out.trim();
}

function viewBoxOf(svg) {
  const m = svg.match(/viewBox="([\d.\s-]+)"/i);
  if (!m) throw new Error("no viewBox");
  const [, , w, h] = m[1].trim().split(/\s+/).map(Number);
  return { w, h };
}

function innerOf(svg) {
  const m = svg.match(/<svg\b[^>]*>([\s\S]*)<\/svg>/i);
  if (!m) throw new Error("no svg body");
  return m[1].trim();
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const entries = [];
for (const { dir, prefix } of SETS) {
  const files = readdirSync(join(SRC_BASE, dir))
    .filter((f) => f.endsWith(".svg"))
    .sort((a, b) => {
      const na = Number(a.replace(prefix, "").replace(".svg", ""));
      const nb = Number(b.replace(prefix, "").replace(".svg", ""));
      return na - nb;
    });
  for (const f of files) {
    const id = f.replace(".svg", "");
    const raw = readFileSync(join(SRC_BASE, dir, f), "utf8");
    const cleaned = clean(raw);
    const { w, h } = viewBoxOf(cleaned);
    writeFileSync(join(OUT_DIR, `${id}.svg`), cleaned);
    entries.push({ id, w, h, inner: innerOf(cleaned) });
  }
}

const manifest = `// AUTO-GENERATED by scripts/build-peeps.mjs — do not edit by hand.
// OpenPeeps flat figures (CC0), tinted via currentColor.

export type PeepMeta = { id: string; w: number; h: number };

export const PEEPS: PeepMeta[] = ${JSON.stringify(
  entries.map(({ id, w, h }) => ({ id, w, h })),
  null,
  2,
)};

export const PEEP_IDS: string[] = PEEPS.map((p) => p.id);

const BY_ID: Record<string, PeepMeta> = Object.fromEntries(
  PEEPS.map((p) => [p.id, p]),
);

export function peepMeta(id: string | null | undefined): PeepMeta | null {
  if (!id) return null;
  return BY_ID[id] ?? null;
}
`;
writeFileSync(MANIFEST, manifest);

console.log(
  `Wrote ${entries.length} peeps to public/peeps/ and the manifest to src/lib/peeps.generated.ts`,
);
